FROM websphere-liberty:22.0.0.9-full-java8-ibmjava

LABEL maintainer="sectroyer <sectroyer@gmail.com>"

COPY ./tobago/tobago-example-demo-5-myfaces-js-test.war /config/dropins/tobago.war

EXPOSE 9080
